# DataSourceController routes
-
  name: 'flowpack/searchplugin - SuggestController->index'
  uriPattern: 'flowpack/searchplugin'
  defaults:
    '@package':    'Flowpack.SearchPlugin'
    '@controller': 'Suggest'
    '@action':     'index'
    '@format':     'json'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']
-
  name: 'flowpack/searchplugin - AjaxSearchController->search'
  uriPattern: 'flowpack/ajaxsearch'
  defaults:
    '@package':    'Flowpack.SearchPlugin'
    '@controller': 'AjaxSearch'
    '@action':     'search'
    '@format':     'html'
  appendExceedingArguments: TRUE
  httpMethods: ['GET']
